import { 
  AgentTask, 
  PermissionLevel, 
  PermissionRequest, 
  PermissionDecision, 
  ActivityLogEntry,
  ToolCall,
  ToolResult
} from '@jarvis/shared';
import { SecurityManager } from '@jarvis/security';
import { ToolRegistry } from '@jarvis/tools';
import { AIFactory } from '@jarvis/ai';

export interface PendingPermission {
  request: PermissionRequest;
  taskId: string;
  toolCall: ToolCall;
  resolve: (decision: PermissionDecision) => void;
}

export class AgentEngine {
  private tasks: Map<string, AgentTask> = new Map();
  private pendingPermissions: Map<string, PendingPermission> = new Map();
  private activityLogs: ActivityLogEntry[] = [];
  private securityManager: SecurityManager;
  private toolRegistry: ToolRegistry;
  private workspaceRoot: string;

  constructor(workspaceRoot: string = 'C:\\JARVIS') {
    this.workspaceRoot = workspaceRoot;
    this.securityManager = new SecurityManager(workspaceRoot);
    this.toolRegistry = new ToolRegistry();
  }

  public getSecurityManager(): SecurityManager {
    return this.securityManager;
  }

  public getToolRegistry(): ToolRegistry {
    return this.toolRegistry;
  }

  public getTasks(): AgentTask[] {
    return Array.from(this.tasks.values()).sort(
      (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
    );
  }

  public getTask(id: string): AgentTask | undefined {
    return this.tasks.get(id);
  }

  public getActivityLogs(): ActivityLogEntry[] {
    return [...this.activityLogs];
  }

  public getPendingPermissions(): PermissionRequest[] {
    return Array.from(this.pendingPermissions.values()).map((p) => p.request);
  }

  private logActivity(
    toolName: string,
    action: string,
    level: PermissionLevel,
    permissionStatus: 'AUTOMATIC' | 'APPROVED' | 'DENIED' | 'BLOCKED',
    status: 'SUCCESS' | 'FAILED' | 'PENDING',
    target?: string
  ): void {
    const entry: ActivityLogEntry = {
      id: 'act_' + Date.now() + Math.random().toString(36).substring(2, 5),
      timestamp: new Date().toISOString(),
      toolName,
      action,
      permissionLevel: level,
      permissionStatus,
      status,
      target,
    };
    this.activityLogs.unshift(entry);
  }

  public async submitTask(userPrompt: string, providerId: string = 'gemini'): Promise<{ task: AgentTask; output?: string }> {
    const taskId = 'task_' + Date.now();
    const task: AgentTask = {
      id: taskId,
      userPrompt,
      status: 'PLANNING',
      steps: [
        { id: 'step_1', description: 'Analyze user intent and identify workspace target', status: 'IN_PROGRESS' },
        { id: 'step_2', description: 'Evaluate security sandbox permission level', status: 'PENDING' },
        { id: 'step_3', description: 'Execute tool operation safely', status: 'PENDING' },
        { id: 'step_4', description: 'Verify outputs and format agent response', status: 'PENDING' },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    this.tasks.set(taskId, task);

    return await this.runTaskPipeline(task, providerId);
  }

  private async runTaskPipeline(task: AgentTask, providerId: string): Promise<{ task: AgentTask; output?: string }> {
    const lower = task.userPrompt.toLowerCase();

    // 1. Analyze intent to deduce tool & level
    let targetTool = 'read_file';
    let toolArgs: Record<string, any> = { filePath: 'package.json' };
    let requiredLevel = PermissionLevel.LEVEL_0_SAFE_READ;
    let targetPath = 'package.json';

    if (lower.includes('list') || lower.includes('dir') || lower.includes('files')) {
      targetTool = 'list_directory';
      toolArgs = { directoryPath: '.' };
      targetPath = this.workspaceRoot;
      requiredLevel = PermissionLevel.LEVEL_0_SAFE_READ;
    } else if (lower.includes('write') || lower.includes('create') || lower.includes('modify') || lower.includes('delete')) {
      targetTool = 'write_file';
      toolArgs = { filePath: 'test-file.txt', content: '// Auto-generated by JARVIS Agent' };
      targetPath = `${this.workspaceRoot}\\test-file.txt`;
      requiredLevel = PermissionLevel.LEVEL_2_USER_CONFIRMATION;
    } else if (lower.includes('search') || lower.includes('find')) {
      targetTool = 'search_files';
      toolArgs = { query: 'JARVIS', directory: '.' };
      targetPath = this.workspaceRoot;
      requiredLevel = PermissionLevel.LEVEL_0_SAFE_READ;
    } else if (lower.includes('test') || lower.includes('npm') || lower.includes('command') || lower.includes('run')) {
      targetTool = 'run_command';
      toolArgs = { command: 'npm test' };
      targetPath = this.workspaceRoot;
      requiredLevel = PermissionLevel.LEVEL_1_SAFE_DEV;
    } else if (lower.includes('git')) {
      targetTool = 'git_status';
      toolArgs = {};
      targetPath = this.workspaceRoot;
      requiredLevel = PermissionLevel.LEVEL_0_SAFE_READ;
    }

    // Step 1 done
    task.steps[0].status = 'DONE';
    task.steps[1].status = 'IN_PROGRESS';
    task.status = 'EXECUTING';

    // Step 2: Evaluate Security Sandwich
    if (targetTool === 'write_file' || requiredLevel === PermissionLevel.LEVEL_2_USER_CONFIRMATION) {
      task.status = 'WAITING_PERMISSION';
      task.steps[1].status = 'IN_PROGRESS';
      task.currentStep = 'Waiting for user authorization for Level 2 write access';

      const reqId = 'perm_' + Date.now();
      const req: PermissionRequest = {
        id: reqId,
        toolName: targetTool,
        targetPath,
        reason: `Agent task requested Level 2 operation: '${task.userPrompt}'`,
        level: PermissionLevel.LEVEL_2_USER_CONFIRMATION,
        timestamp: new Date().toISOString(),
      };

      this.logActivity(targetTool, `Task paused for user permission (${targetTool})`, requiredLevel, 'AUTOMATIC', 'PENDING', targetPath);

      // Create promise for permission resolution
      const permissionDecision = await new Promise<PermissionDecision>((resolve) => {
        const toolCall: ToolCall = {
          id: 'call_' + Date.now(),
          toolName: targetTool,
          args: toolArgs,
          level: requiredLevel,
          reason: task.userPrompt,
        };
        this.pendingPermissions.set(reqId, { request: req, taskId: task.id, toolCall, resolve });
      });

      if (permissionDecision === 'DENY') {
        task.status = 'DENIED';
        task.steps[1].status = 'FAILED';
        task.steps[2].status = 'FAILED';
        task.steps[3].status = 'FAILED';
        task.updatedAt = new Date().toISOString();
        this.logActivity(targetTool, `User explicitly denied task permission`, requiredLevel, 'DENIED', 'FAILED', targetPath);

        return {
          task,
          output: `⚠ Task halted: Permission explicitly denied by user for operation '${targetTool}' on '${targetPath}'.`,
        };
      }

      this.logActivity(targetTool, `User granted permission (${permissionDecision})`, requiredLevel, 'APPROVED', 'SUCCESS', targetPath);
    }

    // Security evaluation passed / approved
    task.steps[1].status = 'DONE';
    task.steps[2].status = 'IN_PROGRESS';

    // Step 3: Execute tool via ToolRegistry
    const toolRes = await this.toolRegistry.executeTool(targetTool, toolArgs, {
      workspaceRoot: this.workspaceRoot,
      securityManager: this.securityManager,
    });

    task.steps[2].status = toolRes.success ? 'DONE' : 'FAILED';
    task.steps[3].status = 'IN_PROGRESS';

    // Step 4: AI Completion synthesis
    const provider = AIFactory.getProvider(providerId);
    const aiResponse = await provider.generateResponse([
      { role: 'user', content: task.userPrompt },
      { role: 'assistant', content: `[Tool Output from ${targetTool}]: ${JSON.stringify(toolRes.output || toolRes.error)}` },
    ]);

    task.steps[3].status = 'DONE';
    task.status = toolRes.success ? 'COMPLETED' : 'FAILED';
    task.updatedAt = new Date().toISOString();

    this.logActivity(
      targetTool,
      `Agent task completed tool execution`,
      toolRes.level,
      'AUTOMATIC',
      toolRes.success ? 'SUCCESS' : 'FAILED',
      targetPath
    );

    return {
      task,
      output: aiResponse.content,
    };
  }

  public respondToPermission(requestId: string, decision: PermissionDecision): boolean {
    const pending = this.pendingPermissions.get(requestId);
    if (!pending) return false;

    this.pendingPermissions.delete(requestId);
    pending.resolve(decision);
    return true;
  }
}
